# nodes/response_node.py

from langchain_core.runnables import RunnableLambda
import os
import logging
from typing import Any, Dict
from Nodes.agent_state import AgentState, update_agent_state

def response_node() -> RunnableLambda:
    """
    Final LangGraph node. Formats and returns the final response to the user, updates AgentState.
    """
    def build_response(state: AgentState) -> AgentState:
        try:
            tool = state.get("tool_name", "unknown")
            output_type = state.get("output_type", "text")
            response = ""
            files = []
            plan_preview = ""
            if output_type == "file":
                # Prefer 'file_path' but also support 'files' (list)
                file_path = state.get("file_path")
                files = state.get("files") or ([file_path] if file_path else [])
                plan_text = state.get("plan_text")
                if plan_text:
                    # Show first 20 lines or 1000 chars
                    lines = plan_text.strip().splitlines()
                    preview = "\n".join(lines[:20])
                    if len(preview) > 1000:
                        preview = preview[:1000] + "..."
                    plan_preview = f"\n\nPreview of Study Plan (first 20 lines):\n{preview}"
                if files:
                    response = f"Output file(s) from '{tool}' are ready:\n" + "\n".join(f"→ {f}" for f in files) + plan_preview
                else:
                    response = f"No valid file found for '{tool}'.{plan_preview}"
            elif output_type == "multi_file":
                paths = state.get("file_path", [])
                valid_files = [p for p in paths if os.path.isfile(p)]
                response = f"{len(valid_files)} file(s) generated by '{tool}'."
                files = valid_files
            elif output_type == "text":
                summary = state.get("summary") or state.get("message") or state.get("response") or "Task completed successfully."
                response = f"Output from '{tool}':\n\n{summary}"
            elif output_type == "alert":
                message = state.get("message", "Alert generated.")
                response = f"Notification from '{tool}':\n\n{message}"
            else:
                response = f"Process by '{tool}' completed. No specific output."
            agent_state = update_agent_state(
                state,
                status="done",
                tool=tool,
                response=response.strip(),
                files=files
            )
            logging.info(f"[Response Node] Response: {response}")
            return agent_state
        except Exception as e:
            logging.error(f"[Response Node] Error: {e}")
            return update_agent_state(state, status="error", error=str(e))
    return RunnableLambda(build_response)
