# nodes/response_node.py

from langchain_core.runnables import RunnableLambda
import os

def response_node() -> RunnableLambda:
    """
    Final LangGraph node. Formats and returns the final response to the user.

    Expected Input:
    {
        "tool_name": <str>,
        "output_type": "file" | "multi_file" | "text" | "alert",
        "file_path": <str> or [<str>],  # optional
        "summary": <str>,               # optional
        "message": <str>,               # optional
    }

    Output:
    {
        "status": "done",
        "tool": <str>,
        "response": <str>,
        "files": [<str>]
    }
    """

    def build_response(state: dict) -> dict:
        tool = state.get("tool_name", "unknown")
        output_type = state.get("output_type", "text")

        response = ""
        files = []

        if output_type == "file":
            path = state.get("file_path")
            if path and os.path.isfile(path):
                response = f"Output file from '{tool}' is ready."
                files = [path]
            else:
                response = f"No valid file found for '{tool}'."

        elif output_type == "multi_file":
            paths = state.get("file_path", [])
            valid_files = [p for p in paths if os.path.isfile(p)]
            response = f"{len(valid_files)} file(s) generated by '{tool}'."
            files = valid_files

        elif output_type == "text":
            summary = state.get("summary") or state.get("message") or "Task completed successfully."
            response = f"Output from '{tool}':\n\n{summary}"

        elif output_type == "alert":
            message = state.get("message", "Alert generated.")
            response = f"Notification from '{tool}':\n\n{message}"

        else:
            response = f"Process by '{tool}' completed. No specific output."

        return {
            "status": "done",
            "tool": tool,
            "response": response.strip(),
            "files": files
        }

    return RunnableLambda(build_response)
